# Site settings
title: Max Quattromani
email: max@maxquattromani.com
description: ""
baseurl: "/maxquattromani"
url: "http://maxquattromani.com"
twitter_username: maxquattromani
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['node_modules', 'scss']
