# Site settings
title: Max Quattromani
email: max@maxquattromani.com
description: ""
baseurl: "/"
url: "http://maxquattromani.com"
twitter_username: maxquattromani
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: true
google_analytics_id: UA-17676310-1
jquery_version: 1.9.0
